# Generated by Django 3.0.5 on 2020-06-04 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contid', models.IntegerField()),
                ('conttype', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('phase', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invitees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfhandle', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=100)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed and with a country code", regex='^\\+?1?\\d{9,15}$')])),
                ('currtime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField(null=True)),
                ('index', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(null=True)),
                ('userssolved', models.IntegerField(null=True)),
                ('tags', models.TextField(null=True)),
            ],
        ),
    ]
